### ISSUE TITLE
Color not changing back to original color

### ISSUE THREAD

**Issue by solowanna** [Jallah123/hue-ambiance#3]
I have the plugin enabled.
Prayer treshhold set to 90 (all other settings are off).

When my prayer gets below 90 the lights flash a blue color.

When i restore my prayer, only the flashing stops but the color stays blue.

Could this be changed so it gets back the original colour before the flash?

**Comment by Jallah123** [comment]
I assume you're not using the ambiance lighting? I will add this feature tomorrow

**Comment by solowanna** [comment]
I'm only using the Prayer and HP setting.
The skybox option is off

**Comment by Jallah123** [comment]
Yes currently that feature is not implemented. The core feature would be the skybox and the rest is extra.

I will put it on the list and implement it soon :)

**Comment by Jallah123** [comment]
fixed in next version
