### ISSUE TITLE
Suggestion list

### ISSUE THREAD

**Issue by Vaksky** [Jallah123/hue-ambiance#7]
![Plugin suggestions](https://user-images.githubusercontent.com/86688601/234771907-da0846cb-967f-4fee-ba27-b7db43b00375.png)

**Comment by Jallah123** [comment]
I created seperate issues for these requests so it's easier to track and maybe other people can implement these aswell

**Comment by Vaksky** [comment]
You're an awesome developer. Thanks (:!
